apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: x8pj978j7-python-gitops
  description: This is GitOps manifest for x8pj978j7-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=x8pj978j7-python
    backstage.io/kubernetes-id: x8pj978j7-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: x8pj978j7-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:x8pj978j7-python
